services:
  - docker

env:
  global:
    - REPO=perrygeo/postgres  # Dockerhub repository name, not github
    - COMMIT=${TRAVIS_COMMIT::8}
    - DATE=`date +%Y%m%d`
    - TAG="$DATE-$COMMIT"

install:
    - make build

script:
    - make test

deploy:
  provider: script
  script: bash docker-push.sh
  on:
      branch: master
